name: Basic Tests and Docker Build 

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - '*'

env:
    DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
    DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    CONTAINER_NAME: discord-liftie-bot

jobs:
  ci-testing:
    # if: false
    name: CI Testing
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Dockerhub Login
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build for Test
        uses: docker/build-push-action@v6
        id: build_for_test
        with:
          push: false
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}

      - name: Docker Run
        id: docker_run
        run: |
          docker images
          docker run -d --name discord-liftie-bot  \
          -e BOT_TOKEN=${{ env.BOT_TOKEN }} \
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
          docker ps
          sleep 3

      - name: Check if data seed exists
        id: run_command
        run: |
          docker exec discord-liftie-bot ls -ltr /app/data/lifts_status.json

      - name: Check container status
        run: |
          container_status=$(docker inspect --format '{{.State.Status}}' ${{ env.CONTAINER_NAME }})
          echo "Container Status: $container_status"
          if [[ "$container_status" != "running" ]]; then
            echo "Error: Docker container did not start correctly!"
            docker logs ${{ env.CONTAINER_NAME }} # Output logs for debugging
            exit 1
          fi

      - name: Check container logs for connection
        run: |
          logs=$(docker logs ${{ env.CONTAINER_NAME }})
          if [[ ! "$logs" =~ "Shard ID None has connected to Gateway" ]]; then
            echo "Warning: Could not find 'Shard ID None has connected to Gateway' in the logs. Bot might not have connected."
            echo "--- Container Logs ---"
            echo "$logs"
          fi

      - name: Stop and remove container
        if: always()
        run: docker stop ${{ env.CONTAINER_NAME }} && docker rm ${{ env.CONTAINER_NAME }}